# Generated by Django 5.0.1 on 2024-03-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_event_created_remove_event_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/events/image/'),
        ),
    ]
